version: '1.0'

services:
  php:
    build: ./php/7.4
    container_name: tools_php-php-7.4
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./php/7.4/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9001:9000"
    depends_on:
      - mysql  
    networks:
      - tools_php-network

  php-8.1:
    build: ./php/8.1
    working_dir: /var/www
    container_name: tools_php-php-8.1
    restart: unless-stopped
    volumes:
      - ./src:/var/www
      - ./php/8.1/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9006:9000"
    depends_on:
      - mysql  
    networks:
      - tools_php-network

  php-8.3:
    build: ./php/8.3/
    working_dir: /var/www
    container_name: tools_php-php-8.3
    restart: unless-stopped
    volumes:
      - ./src:/var/www
      - ./php/8.3/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9007:9000"
    depends_on:
      - mysql  
    networks:
      - tools_php-network

  nginx:
    image: nginx:stable-alpine
    container_name: tools_php-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php 
      - php-8.1 
      - php-8.3 
    networks:
      - tools_php-network  

  mysql:
    image: mysql:8.0.29
    container_name: tools_php-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql_php:/mysql.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - tools_php-network

  phpmyadmin:
    image: phpmyadmin:latest 
    container_name: tools_php-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1024M
      - MEMORY_LIMIT=1024M
      - MAX_EXECUTION_TIME=300  
    ports:
      - 8000:80
    depends_on:
      - mysql 
    networks:
      - tools_php-network        

volumes:
  mysql_php:

networks:
  tools_php-network:
    driver: bridge